version: "3.8"
services:
  gamevault-backend:
    build: .
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USERNAME: gamevault
      DB_PASSWORD: RANDOMPASSWORD
      # The Following Line grants Admin Role to account with this username upon registration.
      SERVER_ADMIN_USERNAME: admin
      # Uncomment and Insert your RAWG API Key here if you have one (https://gamevau.lt/docs/server-docs/indexing-and-metadata#rawg-api-key)
      # RAWG_API_KEY: YOURAPIKEYHERE
    ports:
      - 8080:8080
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: gamevault
      POSTGRES_PASSWORD: RANDOMPASSWORD
      POSTGRES_DB: gamevault
