name: Build and Deploy for Master

on:
  push:
    branches:
      - master
      - hotfix

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Fetch Current Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: phalcode
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: phalcode
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            phalcode/gamevault-backend:latest
            phalcode/gamevault-backend:${{steps.package-version.outputs.current-version}}
            ghcr.io/phalcode/gamevault-backend:latest
            ghcr.io/phalcode/gamevault-backend:${{steps.package-version.outputs.current-version}}
      
      - name: Create Github Tag & Release
        id: release
        uses: CupOfTea696/gh-action-auto-release@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Discord notification
        id: discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_BOT_WEBHOOK }}
        with:
          args: '<@&1128857090090340382> New Release: {{ EVENT_PAYLOAD.repository.full_name }} v${{steps.package-version.outputs.current-version}} has been deployed. Here are the changes: https://github.com/{{EVENT_PAYLOAD.repository.full_name}}/releases/tag/${{steps.package-version.outputs.current-version}}'
