name: Send Discord Notification

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_BOT_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '@everyone New Release: {{ EVENT_PAYLOAD.repository.full_name }} v1.2.0 has been deployed. Here are the changes: https://github.com/Phalcode/crackpipe-backend/releases/latest'
